<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTnCGCxA\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTnCGCxA/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerTnCGCxA.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerTnCGCxA\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerTnCGCxA\App_KernelProdContainer([
    'container.build_hash' => 'TnCGCxA',
    'container.build_id' => 'dc606a85',
    'container.build_time' => 1752865576,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTnCGCxA');
