<?php

namespace ContainerMv5KMVN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FdwsBpuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fdwsBpu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fdwsBpu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rideRepository' => ['privates', 'App\\Repository\\RideRepository', 'getRideRepositoryService', true],
            'avisRepo' => ['privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService', true],
        ], [
            'rideRepository' => 'App\\Repository\\RideRepository',
            'avisRepo' => 'App\\Repository\\AvisRepository',
        ]);
    }
}
