<?php

namespace ContainerMv5KMVN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CFQPgrlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CFQPgrl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CFQPgrl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\SuspendedUserRepository', 'getSuspendedUserRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\SuspendedUserRepository',
        ]);
    }
}
