<?php

namespace ContainerMv5KMVN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateAvisCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateAvisCommand' shared autowired service.
     *
     * @return \App\Command\CreateAvisCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateAvisCommand.php';

        $container->privates['App\\Command\\CreateAvisCommand'] = $instance = new \App\Command\CreateAvisCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('create:test-avis');
        $instance->setDescription('Crée des avis de test pour les trajets.');

        return $instance;
    }
}
