<?php

namespace ContainerMv5KMVN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRideControllersearchRidesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fdwsBpu.App\Controller\RideController::searchRides()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fdwsBpu.App\\Controller\\RideController::searchRides()'] = ($container->privates['.service_locator.fdwsBpu'] ?? $container->load('get_ServiceLocator_FdwsBpuService'))->withContext('App\\Controller\\RideController::searchRides()', $container);
    }
}
