<?php

namespace ContainerMv5KMVN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authenticator_Manager_SecuredAreaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.authenticator.manager.secured_area' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authentication\AuthenticatorManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authentication/AuthenticatorManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authentication/UserAuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authentication/AuthenticatorManager.php';

        return $container->privates['security.authenticator.manager.secured_area'] = new \Symfony\Component\Security\Http\Authentication\AuthenticatorManager([($container->privates['debug.App\\Security\\AppAuthenticator'] ?? $container->load('getAppAuthenticator2Service'))], ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->privates['debug.security.event_dispatcher.secured_area'] ?? self::getDebug_Security_EventDispatcher_SecuredAreaService($container)), 'secured_area', ($container->privates['monolog.logger.security'] ?? self::getMonolog_Logger_SecurityService($container)), true, \Symfony\Component\Security\Http\Authentication\ExposeSecurityLevel::None, []);
    }
}
