<?php

namespace ContainerMv5KMVN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateUserImagesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\UpdateUserImagesCommand' shared autowired service.
     *
     * @return \App\Command\UpdateUserImagesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/UpdateUserImagesCommand.php';

        $container->privates['App\\Command\\UpdateUserImagesCommand'] = $instance = new \App\Command\UpdateUserImagesCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:update-user-images');
        $instance->setDescription('Met à jour les images de profil des utilisateurs.');

        return $instance;
    }
}
