<?php

namespace ContainerTnCGCxA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateRidesCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\CreateRidesCommand' shared autowired service.
     *
     * @return \App\Command\CreateRidesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\CreateRidesCommand'] = $instance = new \App\Command\CreateRidesCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('create:test-rides');

        return $instance;
    }
}
