<?php

namespace ContainerTnCGCxA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateAvisCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\CreateAvisCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\CreateAvisCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('create:test-avis', [], 'Crée des avis de test pour les trajets.', false, #[\Closure(name: 'App\\Command\\CreateAvisCommand')] fn (): \App\Command\CreateAvisCommand => ($container->privates['App\\Command\\CreateAvisCommand'] ?? $container->load('getCreateAvisCommandService')));
    }
}
