<?php

namespace ContainerTnCGCxA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMigrationControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\MigrationController' shared autowired service.
     *
     * @return \App\Controller\MigrationController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MigrationController'] = $instance = new \App\Controller\MigrationController(($container->privates['doctrine.migrations.dependency_factory'] ?? $container->load('getDoctrine_Migrations_DependencyFactoryService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\MigrationController', $container));

        return $instance;
    }
}
