<?php

namespace ContainerTnCGCxA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRideControllerterminateRideService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Xg_gXt6.App\Controller\RideController::terminateRide()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xg_gXt6.App\\Controller\\RideController::terminateRide()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rideRepo' => ['privates', 'App\\Repository\\RideRepository', 'getRideRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'rideRepo' => 'App\\Repository\\RideRepository',
            'em' => '?',
            'mailer' => '?',
        ]))->withContext('App\\Controller\\RideController::terminateRide()', $container);
    }
}
