<?php

namespace ContainerTnCGCxA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Authenticator_LoginService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.firewall.authenticator.login' shared service.
     *
     * @return \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.authenticator.manager.login'] ?? $container->load('getSecurity_Authenticator_Manager_LoginService'));

        if (isset($container->privates['security.firewall.authenticator.login'])) {
            return $container->privates['security.firewall.authenticator.login'];
        }

        return $container->privates['security.firewall.authenticator.login'] = new \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener($a);
    }
}
