<?php

namespace ContainerTnCGCxA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateUserImagesCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\UpdateUserImagesCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\UpdateUserImagesCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:update-user-images', [], 'Met à jour les images de profil des utilisateurs.', false, #[\Closure(name: 'App\\Command\\UpdateUserImagesCommand')] fn (): \App\Command\UpdateUserImagesCommand => ($container->privates['App\\Command\\UpdateUserImagesCommand'] ?? $container->load('getUpdateUserImagesCommandService')));
    }
}
