<?php

namespace ContainerTnCGCxA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllergetDriverAverageRatingService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Cj.T6dF.App\Controller\UserController::getDriverAverageRating()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Cj.T6dF.App\\Controller\\UserController::getDriverAverageRating()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', 'App\\Entity\\User', 'getUserService', true],
            'avisRepo' => ['privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'avisRepo' => 'App\\Repository\\AvisRepository',
        ]))->withContext('App\\Controller\\UserController::getDriverAverageRating()', $container);
    }
}
