# config/services.yaml
parameters:
    env(ORS_API_KEY): '%env(ORS_API_KEY)%'

services:
    App\EventListener\CorsPreflightRequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 255 }

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    Doctrine\Migrations\DependencyFactory:
        alias: 'doctrine.migrations.dependency_factory'
