services:
  - type: web
    name: ecoride-back
    env: php
    plan: free
    rootDir: backend        
    docRoot: public        
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "php -S 0.0.0.0:$PORT -t public"
    envVars:
      - key: APP_ENV
        value: prod
