# backend/.render.yaml

services:
  - type: web
    name: ecoride-back
    env: docker
    plan: free
    rootDir: .
    buildCommand: ""
    startCommand: apache2-foreground
    envVars:
      - key: APP_ENV
        value: prod
