services:
  - type: web
    name: ecoride-back
    env: docker
    plan: free
    rootDir: .
    buildCommand: ""
    startCommand: |
      php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
      php bin/console cache:clear --env=prod
      php bin/console cache:warmup --env=prod
      apache2-foreground
    envVars:
      - key: APP_ENV
        value: prod
