services:
  - type: web
    name: ecoride-back
    env: php                    
    plan: free
    rootDir: .
    docRoot: public              
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "apache2-foreground"
    envVars:
      - key: APP_ENV
        value: prod
