<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMv5KMVN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMv5KMVN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMv5KMVN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMv5KMVN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMv5KMVN\App_KernelDevDebugContainer([
    'container.build_hash' => 'Mv5KMVN',
    'container.build_id' => 'f93a33bd',
    'container.build_time' => 1752910456,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMv5KMVN');
