doctrine:
    dbal:
        # URL de connexion principale, définie dans .env (DATABASE_URL)
        url: '%env(resolve:DATABASE_URL)%'

        # Version du serveur PostgreSQL utilisé par Render
        server_version: '16.9'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

    orm:
        # Stratégie de nommage underscore + numéros ("user_id" plutôt que "userId")
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware

        auto_generate_proxy_classes: '%kernel.debug%'           # true en dev, false en prod
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'     # là où sont générés les proxies
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true

        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity

        auto_mapping: true
        mappings:
            App:
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

# ----- Surcharge pour l’environnement de test -----
when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

# ----- Surcharge pour l’environnement de production -----
when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
