lexik_jwt_authentication:
    secret_key:  '%env(resolve:JWT_PRIVATE_KEY_PATH)%'
    public_key:  '%env(resolve:JWT_PUBLIC_KEY_PATH)%'  
    pass_phrase: '2025EcoRideHoche'
    token_ttl: 3600 # Durée de validité du token en secondes