nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:4200']
        allow_methods: ['POST', 'GET', 'OPTIONS']
        allow_headers: ['Content-Type']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:4200']
