nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: 
      - 'https://zh-ecoride-frontend-7b5170b8d71e.herokuapp.com'
      - 'http://localhost:54518'
      - '*'
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    max_age: 3600

  paths:
    '^/api/':
      allow_origin: 
        - 'https://zh-ecoride-frontend-7b5170b8d71e.herokuapp.com'
        - 'http://localhost:54518'
        - '*'
      allow_credentials: true
      allow_headers: ['Content-Type', 'Authorization']
      allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
      max_age: 3600
