<?php

namespace ContainerYejZbx5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllergetSuspendedEmailsService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.CFQPgrl.App\Controller\AdminController::getSuspendedEmails()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CFQPgrl.App\\Controller\\AdminController::getSuspendedEmails()'] = ($container->privates['.service_locator.CFQPgrl'] ?? $container->load('get_ServiceLocator_CFQPgrlService'))->withContext('App\\Controller\\AdminController::getSuspendedEmails()', $container);
    }
}
