<?php

namespace ContainerYejZbx5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateVehiclesCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\CreateVehiclesCommand' shared autowired service.
     *
     * @return \App\Command\CreateVehiclesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\CreateVehiclesCommand'] = $instance = new \App\Command\CreateVehiclesCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('create:test-vehicles');

        return $instance;
    }
}
