<?php

namespace ContainerYejZbx5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRideRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\RideRepository' shared autowired service.
     *
     * @return \App\Repository\RideRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\RideRepository'] = new \App\Repository\RideRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
