<?php

namespace ContainerYejZbx5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Authenticator_ApiService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.firewall.authenticator.api' shared service.
     *
     * @return \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.authenticator.manager.api'] ?? $container->load('getSecurity_Authenticator_Manager_ApiService'));

        if (isset($container->privates['security.firewall.authenticator.api'])) {
            return $container->privates['security.firewall.authenticator.api'];
        }

        return $container->privates['security.firewall.authenticator.api'] = new \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener($a);
    }
}
