<?php

namespace ContainerYejZbx5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserTypeFormService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\UserTypeForm' shared autowired service.
     *
     * @return \App\Form\UserTypeForm
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\UserTypeForm'] = new \App\Form\UserTypeForm();
    }
}
