<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXKewKTr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXKewKTr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXKewKTr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXKewKTr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXKewKTr\App_KernelDevDebugContainer([
    'container.build_hash' => 'XKewKTr',
    'container.build_id' => '535e1f11',
    'container.build_time' => 1751727374,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXKewKTr');
