<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIEIWVII\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIEIWVII/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIEIWVII.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIEIWVII\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIEIWVII\App_KernelDevDebugContainer([
    'container.build_hash' => 'IEIWVII',
    'container.build_id' => 'a3d3e839',
    'container.build_time' => 1750275295,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIEIWVII');
