<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRd41YYb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRd41YYb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRd41YYb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRd41YYb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRd41YYb\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rd41YYb',
    'container.build_id' => 'c075d5c0',
    'container.build_time' => 1752090947,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRd41YYb');
