<?php

namespace Container8oL8jax;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_ValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'twig.validator' shared service.
     *
     * @return \Symfony\Bridge\Twig\Validator\Constraints\TwigValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/twig-bridge/Validator/Constraints/TwigValidator.php';

        $a = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->privates['twig.validator'])) {
            return $container->privates['twig.validator'];
        }

        return $container->privates['twig.validator'] = new \Symfony\Bridge\Twig\Validator\Constraints\TwigValidator($a);
    }
}
