<?php

namespace Container8oL8jax;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUriSignerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'uri_signer' shared service.
     *
     * @return \Symfony\Component\HttpFoundation\UriSigner
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['uri_signer'] = new \ReflectionClass('Symfony\Component\HttpFoundation\UriSigner')->newLazyGhost(static function ($proxy) use ($container) { self::do($container, $proxy); });
        }

        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/UriSigner.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/clock/src/ClockInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/clock/ClockInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/clock/Clock.php';

        return ($lazyLoad->__construct($container->getParameter('kernel.secret'), '_hash', '_expiration', ($container->privates['clock'] ??= new \Symfony\Component\Clock\Clock())) && false ?: $lazyLoad);
    }
}
