<?php

namespace Container8oL8jax;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserTypeFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\UserTypeForm' shared autowired service.
     *
     * @return \App\Form\UserTypeForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/UserTypeForm.php';

        return $container->privates['App\\Form\\UserTypeForm'] = new \App\Form\UserTypeForm();
    }
}
