<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'credits' => [parent::class, 'credits', null, 16],
        "\0".parent::class."\0".'driverPreferences' => [parent::class, 'driverPreferences', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'gender' => [parent::class, 'gender', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null, 16],
        "\0".parent::class."\0".'isVerified' => [parent::class, 'isVerified', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'pseudo' => [parent::class, 'pseudo', null, 16],
        "\0".parent::class."\0".'rating' => [parent::class, 'rating', null, 16],
        "\0".parent::class."\0".'ridesAsDriver' => [parent::class, 'ridesAsDriver', null, 16],
        "\0".parent::class."\0".'ridesAsPassenger' => [parent::class, 'ridesAsPassenger', null, 16],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null, 16],
        "\0".parent::class."\0".'vehicles' => [parent::class, 'vehicles', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'credits' => [parent::class, 'credits', null, 16],
        'driverPreferences' => [parent::class, 'driverPreferences', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'gender' => [parent::class, 'gender', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'image' => [parent::class, 'image', null, 16],
        'isVerified' => [parent::class, 'isVerified', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'pseudo' => [parent::class, 'pseudo', null, 16],
        'rating' => [parent::class, 'rating', null, 16],
        'ridesAsDriver' => [parent::class, 'ridesAsDriver', null, 16],
        'ridesAsPassenger' => [parent::class, 'ridesAsPassenger', null, 16],
        'roles' => [parent::class, 'roles', null, 16],
        'vehicles' => [parent::class, 'vehicles', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
