<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ride extends \App\Entity\Ride implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'arrival' => [parent::class, 'arrival', null, 16],
        "\0".parent::class."\0".'availableSeats' => [parent::class, 'availableSeats', null, 16],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null, 16],
        "\0".parent::class."\0".'departure' => [parent::class, 'departure', null, 16],
        "\0".parent::class."\0".'driver' => [parent::class, 'driver', null, 16],
        "\0".parent::class."\0".'extras' => [parent::class, 'extras', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'initialSeats' => [parent::class, 'initialSeats', null, 16],
        "\0".parent::class."\0".'passengers' => [parent::class, 'passengers', null, 16],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'vehicle' => [parent::class, 'vehicle', null, 16],
        'arrival' => [parent::class, 'arrival', null, 16],
        'availableSeats' => [parent::class, 'availableSeats', null, 16],
        'date' => [parent::class, 'date', null, 16],
        'departure' => [parent::class, 'departure', null, 16],
        'driver' => [parent::class, 'driver', null, 16],
        'extras' => [parent::class, 'extras', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'initialSeats' => [parent::class, 'initialSeats', null, 16],
        'passengers' => [parent::class, 'passengers', null, 16],
        'price' => [parent::class, 'price', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'vehicle' => [parent::class, 'vehicle', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
