<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Avis extends \App\Entity\Avis implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'comment' => [parent::class, 'comment', null, 16],
        "\0".parent::class."\0".'driver' => [parent::class, 'driver', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isValidated' => [parent::class, 'isValidated', null, 16],
        "\0".parent::class."\0".'passenger' => [parent::class, 'passenger', null, 16],
        "\0".parent::class."\0".'rating' => [parent::class, 'rating', null, 16],
        "\0".parent::class."\0".'ride' => [parent::class, 'ride', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'token' => [parent::class, 'token', null, 16],
        'comment' => [parent::class, 'comment', null, 16],
        'driver' => [parent::class, 'driver', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isValidated' => [parent::class, 'isValidated', null, 16],
        'passenger' => [parent::class, 'passenger', null, 16],
        'rating' => [parent::class, 'rating', null, 16],
        'ride' => [parent::class, 'ride', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'token' => [parent::class, 'token', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
